version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "security"
    # Specify who should review when dependencies are updated
    reviewers:
      - "teamgofer"
    # Raise pull requests for version updates
    # to npm packages with a version update
    versioning-strategy: increase
    # Add assignees
    assignees:
      - "teamgofer"
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 10
    # Only security updates for development dependencies
    allow:
      - dependency-type: "production"
    # Ignore certain dependencies
    ignore:
      # Ignore major updates for these packages
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
    # Raise pull requests for version updates
    # to github-actions with a version update
    versioning-strategy: increase
    # Allow up to 10 open pull requests for github-actions
    open-pull-requests-limit: 10 