import type { GeolocationPosition, LocationOptions, LocationCallback, ErrorCallback, Geofence, LocationHistoryEntry } from '../types/geolocation';
export declare class LocationService {
    private lastLocation;
    private watchId;
    private minDistanceThreshold;
    private readonly _locationEmitter;
    private readonly _errorEmitter;
    private _isTracking;
    private _retryCount;
    private readonly _maxRetries;
    private readonly _options;
    private readonly _errorHandler;
    private readonly _monitor;
    private readonly _geofenceService;
    private readonly _historyService;
    constructor(options?: Partial<LocationOptions>);
    startTracking(): Promise<void>;
    stopTracking(): void;
    getCurrentLocation(): Promise<GeolocationPosition>;
    onLocationChange(callback: LocationCallback): () => void;
    offLocationChange(callback: LocationCallback): void;
    onError(callback: ErrorCallback): () => void;
    offError(callback: ErrorCallback): void;
    private _handlePositionSuccess;
    private _handlePositionError;
    private _handleError;
    private _retryTracking;
    private _getFreshLocation;
    private _getDefaultLocation;
    private _isCacheExpired;
    private _notifyLocation;
    private _notifyError;
    getCurrentSpeed(): number | null;
    getCurrentHeading(): number | null;
    getCurrentAccuracy(): number | null;
    isIndoors(threshold?: number): boolean;
    getCurrentAltitude(): number | null;
    getCurrentAltitudeAccuracy(): number | null;
    addGeofence(geofence: Geofence): void;
    removeGeofence(id: string): void;
    getActiveGeofences(): Geofence[];
    onGeofenceEnter(callback: (geofence: Geofence) => void): () => void;
    onGeofenceExit(callback: (geofence: Geofence) => void): () => void;
    onGeofenceDwell(callback: (data: {
        geofence: Geofence;
        duration: number;
    }) => void): () => void;
    getLocationHistory(startTime?: number, endTime?: number): LocationHistoryEntry[];
    getRecentHistory(duration: number): LocationHistoryEntry[];
    getHistoryInRange(latitude: number, longitude: number, radius: number): LocationHistoryEntry[];
    clearHistory(): void;
}
