#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting on staged files
npx lint-staged

# Run unit tests
npm test -- --findRelatedTests $(git diff --cached --name-only | grep -E '\.jsx?$') 